name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: chip8-linux
            output_name: chip8
          - os: macos-latest
            artifact_name: chip8-macos
            output_name: chip8
          - os: windows-latest
            artifact_name: chip8-windows
            output_name: chip8.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux Build Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev cmake

      - name: Build Raylib & Project (Linux)
        if: runner.os == 'Linux'
        run: |
          git clone --depth 1 https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=STATIC
          cd ../..
          gcc main.c -Iraylib/src -Lraylib/src -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o ${{ matrix.output_name }}

      - name: Install dependencies & Build (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install raylib
          clang main.c $(pkg-config --cflags --libs raylib) -o ${{ matrix.output_name }}

      - name: Build Raylib & Project (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          git clone --depth 1 https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_DESKTOP CC=gcc
          cd ../..
          gcc main.c -Iraylib/src -Lraylib/src -lraylib -lopengl32 -lgdi32 -lwinmm -o ${{ matrix.output_name }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.output_name }}